version: "3.4" # if no version is specificed then v1 is assumed. Recommend v2 minimum

services:
  target1:
    build:
      context: .
      dockerfile: ubuntu-ssh.Dockerfile
    image: ubuntu-custom
    hostname: ubuntu1
    ports:
      - "2222:22"

  target2:
    build:
      context: .
      dockerfile: centos-ssh.Dockerfile
    image: centos-custom
    hostname: centos1
    ports:
      - "2224:22"
